sudo: required
language: generic 
services:
  - docker
before_install:
  docker build -t sgnarl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sgnarl/react-test npm test

after_success:
  - docker build -t sgnarl/multi-client ./client
  - docker build -t sgnarl/multi-nginx ./nginx
  - docker build -t sgnarl/multi-server ./server
  - docker build -t sgnarl/multi-worker ./worker
  #Log in to the docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push sgnarl/multi-client
  - docker push sgnarl/multi-nginx
  - docker push sgnarl/multi-server
  - docker push sgnarl/multi-worker
